<?php

class WishManager extends Model
{
    public function getWishlist($iduser)
    {
        $s = $this->getWithParams('*','wish','WHERE id_user = '.$iduser.';', 'Wish');
        var_dump($s);
        return $s;
    }
    public function addWithParams($table, $params)
    {
       parent::addWithParams($table, ''.$params.','.$_SESSION["id"].''); // TODO: Change the autogenerated stub
    }
    public function removeWish($table, $isbn){
        $this->removeWithParams($table, 'id_user = '.$_SESSION["id"].' and ISBN = '.$isbn.'');
    }



}